services:

  backend:
    build: ./
    restart: always
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
    
  tika:
    image: apache/tika
    ports:
        - 9998:9998
  
  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
